CREATE TABLE TABLE_2 (
       COLUMN_1 CHAR(10) NOT NULL
     , COLUMN_2 CHAR(10) NOT NULL
     , PRIMARY KEY (COLUMN_1, COLUMN_2)
);

CREATE TABLE TABLE_1 (
       COLUMN_1 CHAR(10) NOT NULL
     , COLUMN_2 CHAR(10)
     , PRIMARY KEY (COLUMN_1)
     , CONSTRAINT FK_TABLE_1_1 FOREIGN KEY (COLUMN_1, COLUMN_2)
                  REFERENCES TABLE_2 (COLUMN_1, COLUMN_2)
);

CREATE TABLE TABLE_3 (
       COLUMN_1 CHAR(10)
     , COLUMN_2 CHAR(10)
     , COLUMN_3 CHAR(10)
     , CONSTRAINT FK_TABLE_3_1 FOREIGN KEY (COLUMN_2, COLUMN_2)
                  REFERENCES TABLE_2 (COLUMN_1, COLUMN_2)
);

